name: STXCluster
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6    # Python version 3.6
    - bottleneck    # C-optimized array functions for NumPy
    - colorcet      # Collection of perceptually uniform colormaps 
    - cython        # required for pystan
    - ipython       # IPython interpreter and tools
    - joblib        # parallel execution
    - jupyter       # notebooks
    - matplotlib    # 2D plotting library
    - mypy          # catch many common issues
    - netcdf4       # xarray file i/o
    - numpy         # N-d array and numerics
    - pandas        # Labeled array library
    - pickle        # save objects (ie stan models)
    - pomegranate   # Hidden Markov Model implementation
    - pylint        # catch other issues
    - pystan        # python interface to stan modeling language
    - scipy         # Common math/stats/science functions
    - seaborn       # statistical plots including heatmap
    - xarray        # N-d labeled array library